=== alurue9140/RETO-1/XSD/Empleados.xsd
<?xml version="1.0" encoding="UTF-8" standalone="no"?>

<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema">
  <xs:element name="Empleados">
    <xs:complexType>
      <xs:sequence>
        <xs:element name="Empleado" maxOccurs="unbounded" minOccurs="0">
          <xs:complexType>
            <xs:sequence>
              <xs:element type="xs:string" name="nif"/>
              <xs:element type="xs:string" name="Nombre"/>
              <xs:element type="xs:string" name="Apellido1"/>
              <xs:element type="xs:string" name="Apellido2"/>
              <xs:element type="xs:string" name="cuenta"/>
              <xs:element type="xs:date" name="Antigüedad"/>
              <xs:element type="xs:string" name="N._de_afiliación_a_la_Seguridad_Social"/>
              <xs:element type="xs:string" name="Categoría-Grupo_profesional"/>
              <xs:element type="xs:byte" name="Grupo_Cotización"/>
              <xs:element type="xs:string" name="email"/>
              <xs:element type="xs:string" name="departamento"/>
            </xs:sequence>
          </xs:complexType>
        </xs:element>
      </xs:sequence>
    </xs:complexType>
  </xs:element>
</xs:schema>

=== alurue9140/RETO-1/XSD/Empleados.xml
<?xml version="1.0" encoding="UTF-8" standalone="no"?>

<Empleados xmlns:xs="http://www.w3.org/2001/XMLSchema-instance" xs:noNamespaceSchemaLocation="Empleados.xsd">
    <Empleado>
        <nif>12345696-S</nif>
        <Nombre>ANTONIO</Nombre>
        <Apellido1>CAMPOS</Apellido1>
        <Apellido2>GALLEGO</Apellido2>
        <cuenta>acamposg</cuenta>
        <Antigüedad>2012-02-26</Antigüedad>
        <N._de_afiliación_a_la_Seguridad_Social />
        <Categoría-Grupo_profesional>B3</Categoría-Grupo_profesional>
        <Grupo_Cotización>6</Grupo_Cotización>
        <email>acamposg@empresa1.com</email>
        <departamento>1</departamento>
        <sou_base>1000</sou_base>
        <horas>180</horas>
    </Empleado>
    <Empleado>
        <nif>12345698-U</nif>
        <Nombre>PEPE</Nombre>
        <Apellido1>CHAVES</Apellido1>
        <Apellido2>CAMPOS</Apellido2>
        <cuenta>pchavesc</cuenta>
        <Antigüedad>2019-05-20</Antigüedad>
        <N._de_afiliación_a_la_Seguridad_Social />
        <Categoría-Grupo_profesional>A3</Categoría-Grupo_profesional>
        <Grupo_Cotización>6</Grupo_Cotización>
        <email>pchavesc@empresa1.com</email>
        <departamento>1</departamento>
        <sou_base>1000</sou_base>
        <horas>180</horas> 
    </Empleado>
    <Empleado>
        <nif>12345693-P</nif>
        <Nombre>IGNACIO</Nombre>
        <Apellido1>CHAVES</Apellido1>
        <Apellido2>VARGAS</Apellido2>
        <cuenta>ichavesv</cuenta>
        <Antigüedad>2022-09-06</Antigüedad>
        <N._de_afiliación_a_la_Seguridad_Social />
        <Categoría-Grupo_profesional>B3</Categoría-Grupo_profesional>
        <Grupo_Cotización>7</Grupo_Cotización>
        <email>ichavesv@empresa1.com</email>
        <departamento>1</departamento>
        <sou_base>1000</sou_base>
        <horas>180</horas> 
    </Empleado>
    <Empleado>
        <nif>12345690-M</nif>
        <Nombre>FRANCISCO</Nombre>
        <Apellido1>COELLO</Apellido1>
        <Apellido2>ALABAU</Apellido2>
        <cuenta>fcoelloa</cuenta>
        <Antigüedad>2017-02-26</Antigüedad>
        <N._de_afiliación_a_la_Seguridad_Social />
        <Categoría-Grupo_profesional>B2</Categoría-Grupo_profesional>
        <Grupo_Cotización>6</Grupo_Cotización>
        <email>fcoelloa@empresa1.com</email>
        <departamento>1</departamento>
        <sou_base>1000</sou_base>
        <horas>180</horas> 
    </Empleado>
    <Empleado>
        <nif>12345678-A</nif>
        <Nombre>LUIS</Nombre>
        <Apellido1>NAVARRO</Apellido1>
        <Apellido2>RUIZ</Apellido2>
        <cuenta>lnavarror</cuenta>
        <Antigüedad>2022-12-22</Antigüedad>
        <N._de_afiliación_a_la_Seguridad_Social />
        <Categoría-Grupo_profesional>A1</Categoría-Grupo_profesional>
        <Grupo_Cotización>4</Grupo_Cotización>
        <email>lnavarror@empresa1.com</email>
        <departamento>1</departamento>
        <sou_base>1000</sou_base>
        <horas>180</horas> 
    </Empleado>
    <Empleado>
        <nif>12345691-N</nif>
        <Nombre>BASILIO</Nombre>
        <Apellido1>PUJOL</Apellido1>
        <Apellido2>GOMIS</Apellido2>
        <cuenta>bpujolg</cuenta>
        <Antigüedad>2016-04-19</Antigüedad>
        <N._de_afiliación_a_la_Seguridad_Social />
        <Categoría-Grupo_profesional>B1</Categoría-Grupo_profesional>
        <Grupo_Cotización>1</Grupo_Cotización>
        <email>bpujolg@empresa1.com</email>
        <departamento>1</departamento>
        <sou_base>1000</sou_base>
        <horas>180</horas> 
    </Empleado>
    <Empleado>
        <nif>12345694-Q</nif>
        <Nombre>LAURA</Nombre>
        <Apellido1>ALBA</Apellido1>
        <Apellido2>ARIAS</Apellido2>
        <cuenta>lalbaa</cuenta>
        <Antigüedad>2019-04-16</Antigüedad>
        <N._de_afiliación_a_la_Seguridad_Social />
        <Categoría-Grupo_profesional>A1</Categoría-Grupo_profesional>
        <Grupo_Cotización>5</Grupo_Cotización>
        <email>lalbaa@empresa1.com</email>
        <departamento>2</departamento>
        <sou_base>1000</sou_base>
        <horas>180</horas> 
    </Empleado>
    <Empleado>
        <nif>12345683-F</nif>
        <Nombre>JAVIER</Nombre>
        <Apellido1>ARIAS</Apellido1>
        <Apellido2>PUJOL</Apellido2>
        <cuenta>jariasp</cuenta>
        <Antigüedad>2022-12-25</Antigüedad>
        <N._de_afiliación_a_la_Seguridad_Social />
        <Categoría-Grupo_profesional>B3</Categoría-Grupo_profesional>
        <Grupo_Cotización>4</Grupo_Cotización>
        <email>jariasp@empresa1.com</email>
        <departamento>2</departamento>
        <sou_base>1000</sou_base>
        <horas>180</horas> 
    </Empleado>
    <Empleado>
        <nif>12345697-T</nif>
        <Nombre>CLAUDIO</Nombre>
        <Apellido1>MONCHO</Apellido1>
        <Apellido2>AGUILAR</Apellido2>
        <cuenta>cmonchoa</cuenta>
        <Antigüedad>2013-12-22</Antigüedad>
        <N._de_afiliación_a_la_Seguridad_Social />
        <Categoría-Grupo_profesional>A3</Categoría-Grupo_profesional>
        <Grupo_Cotización>3</Grupo_Cotización>
        <email>cmonchoa@empresa1.com</email>
        <departamento>2</departamento>
        <sou_base>1000</sou_base>
        <horas>180</horas> 
    </Empleado>
    <Empleado>
        <nif>12345702-Y</nif>
        <Nombre>BASILIO</Nombre>
        <Apellido1>MONCHO</Apellido1>
        <Apellido2>COELLO</Apellido2>
        <cuenta>bmonchoc</cuenta>
        <Antigüedad>2011-04-08</Antigüedad>
        <N._de_afiliación_a_la_Seguridad_Social />
        <Categoría-Grupo_profesional>A3</Categoría-Grupo_profesional>
        <Grupo_Cotización>5</Grupo_Cotización>
        <email>bmonchoc@empresa1.com</email>
        <departamento>2</departamento>
        <sou_base>1000</sou_base>
        <horas>180</horas> 
    </Empleado>
    <Empleado>
        <nif>12345686-I</nif>
        <Nombre>JOHANN</Nombre>
        <Apellido1>AGUILAR</Apellido1>
        <Apellido2>ALBA</Apellido2>
        <cuenta>jaguilara</cuenta>
        <Antigüedad>2016-04-30</Antigüedad>
        <N._de_afiliación_a_la_Seguridad_Social />
        <Categoría-Grupo_profesional>A3</Categoría-Grupo_profesional>
        <Grupo_Cotización>2</Grupo_Cotización>
        <email>jaguilara@empresa1.com</email>
        <departamento>3</departamento>
        <sou_base>1000</sou_base>
        <horas>180</horas> 
    </Empleado>
    <Empleado>
        <nif>12345679-B</nif>
        <Nombre>SUSANA</Nombre>
        <Apellido1>ALABAU</Apellido1>
        <Apellido2>SANCHO</Apellido2>
        <cuenta>salabaus</cuenta>
        <Antigüedad>2022-12-16</Antigüedad>
        <N._de_afiliación_a_la_Seguridad_Social />
        <Categoría-Grupo_profesional>B3</Categoría-Grupo_profesional>
        <Grupo_Cotización>4</Grupo_Cotización>
        <email>salabaus@empresa1.com</email>
        <departamento>3</departamento>
        <sou_base>1000</sou_base>
        <horas>180</horas> 
    </Empleado>
    <Empleado>
        <nif>12345705-B</nif>
        <Nombre>LAURA</Nombre>
        <Apellido1>ALBA</Apellido1>
        <Apellido2>ALABAU</Apellido2>
        <cuenta>lalbaa</cuenta>
        <Antigüedad>2014-01-12</Antigüedad>
        <N._de_afiliación_a_la_Seguridad_Social />
        <Categoría-Grupo_profesional>A1</Categoría-Grupo_profesional>
        <Grupo_Cotización>4</Grupo_Cotización>
        <email>lalbaa@empresa1.com</email>
        <departamento>3</departamento>
        <sou_base>1000</sou_base>
        <horas>180</horas> 
    </Empleado>
    <Empleado>
        <nif>12345699-V</nif>
        <Nombre>SARA</Nombre>
        <Apellido1>ALBA</Apellido1>
        <Apellido2>MONCHO</Apellido2>
        <cuenta>salbam</cuenta>
        <Antigüedad>2017-06-04</Antigüedad>
        <N._de_afiliación_a_la_Seguridad_Social />
        <Categoría-Grupo_profesional>B1</Categoría-Grupo_profesional>
        <Grupo_Cotización>4</Grupo_Cotización>
        <email>salbam@empresa1.com</email>
        <departamento>3</departamento>
        <sou_base>1000</sou_base>
        <horas>180</horas> 
    </Empleado>
    <Empleado>
        <nif>12345701-X</nif>
        <Nombre>FRANCISCO</Nombre>
        <Apellido1>CAMPOS</Apellido1>
        <Apellido2>GOMIS</Apellido2>
        <cuenta>fcamposg</cuenta>
        <Antigüedad>2018-11-04</Antigüedad>
        <N._de_afiliación_a_la_Seguridad_Social />
        <Categoría-Grupo_profesional>B2</Categoría-Grupo_profesional>
        <Grupo_Cotización>4</Grupo_Cotización>
        <email>fcamposg@empresa1.com</email>
        <departamento>3</departamento>
        <sou_base>1000</sou_base>
        <horas>180</horas> 
    </Empleado>
    <Empleado>
        <nif>12345706-C</nif>
        <Nombre>JORGE</Nombre>
        <Apellido1>CARVALHO</Apellido1>
        <Apellido2>GOMIS</Apellido2>
        <cuenta>jcarvalhog</cuenta>
        <Antigüedad>2012-07-19</Antigüedad>
        <N._de_afiliación_a_la_Seguridad_Social />
        <Categoría-Grupo_profesional>A1</Categoría-Grupo_profesional>
        <Grupo_Cotización>2</Grupo_Cotización>
        <email>jcarvalhog@empresa1.com</email>
        <departamento>3</departamento>
        <sou_base>1000</sou_base>
        <horas>180</horas> 
    </Empleado>
    <Empleado>
        <nif>12345685-H</nif>
        <Nombre>RODRIGO</Nombre>
        <Apellido1>GALLEGO</Apellido1>
        <Apellido2>CHAVES</Apellido2>
        <cuenta>rgallegoc</cuenta>
        <Antigüedad>2023-02-01</Antigüedad>
        <N._de_afiliación_a_la_Seguridad_Social />
        <Categoría-Grupo_profesional>B2</Categoría-Grupo_profesional>
        <Grupo_Cotización>6</Grupo_Cotización>
        <email>rgallegoc@empresa1.com</email>
        <departamento>3</departamento>
        <sou_base>1000</sou_base>
        <horas>180</horas> 
    </Empleado>
    <Empleado>
        <nif>12345680-C</nif>
        <Nombre>PEDRO</Nombre>
        <Apellido1>GOMIS</Apellido1>
        <Apellido2>ZAMBUJO</Apellido2>
        <cuenta>pgomisz</cuenta>
        <Antigüedad>2022-12-29</Antigüedad>
        <N._de_afiliación_a_la_Seguridad_Social />
